# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ea5eebe5fa3bd6078aaf794bb70ea5dd670714c089c0f35ecaadf9d7d71baa819833e9e717eba4c7a4badb78a703b4fad9e1254678fdac62674ff5c56405aa6a

test:
  secret_key_base: 78b56d415e8afbe217068346c3fe206c355312e7396546c4cb80754d9f9c96dd8c28750e7630127cddb8143ba344315ba392b191dafee08db8b7c4f1bc3a73ee

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
